---
abstract: 'Read files and directories from Github'
author:
  - 'Shmuel Fomberg <shmuelfomberg@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Github-Files
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  File::Spec: 0
  JSON: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 6.04
version: 0.12
